---
- hosts: localhost
  connection: local
 
  tasks:
    - name: install git
      apt: pkg=git state=installed update_cache=true

    - name: install cmake
      apt: name=cmake state=installed update_cache=true

    - name: install sqlite
      apt: name=libsqlite3-dev state=installed update_cache=true

    - name: get gtest
      unarchive: src=https://github.com/google/googletest/archive/release-1.7.0.tar.gz dest=/opt/gtest copy=no
    
    - name: create lib for gtest
      file: path=/opt/gtest/lib state=directory
     
    - name: build gtest
      shell: cd /opt/gtest/lib; cmake ..; make
