- name: configure prerequisites
  hosts: [host_testers, guest_testers]
  roles:
    - common
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','http_proxy') }}"
  tags: [host, guest]

- name: perform host tests
  hosts: host_testers
  roles:
    - host_tester
  tags: host

- name: prepare for guest tests with STORAGE_STRATEGY_SECTOR
  hosts: guest_testers
  roles:
    - { role: guest_tester_pre, ssd_storage_strategy: 1 }
  tags: guest

- name: perform guest tests with STORAGE_STRATEGY_SECTOR
  hosts: guests
  roles:
    - guest_tester
  tags: guest

- name: prepare for guest tests with STORAGE_STRATEGY_OBJECT
  hosts: guest_testers
  roles:
    - { role: guest_tester_pre, ssd_storage_strategy: 2 }
  tags: guest

- name: perform guest tests with STORAGE_STRATEGY_OBJECT
  hosts: guests
  roles:
    - guest_tester
  tags: guest

- name: clean up after guest tests
  hosts: guest_testers
  roles:
    - { role: guest_tester_pre, cleanup_only: true }
  tags: guest
