#!/bin/bash
# This file used for linking : QEMU <-> SSD FTL SOURCE
# For "SSD PAGE MAPPING FTL"
# Usage : Just typing your shell -> " $./link_pm "


# ------------------- Source File location -----------------------      ----- linked file destination ----

#./unlink_last
#./unlink_fast

# Link make file configuration
ln -s ../CONFIG/QEMU_MAKEFILE/Makefile_pm				../Makefile.target

# SSD operation control header file "common.h"
ln -s ../../FTL_SOURCE/COMMON/common.h					../hw/common.h
ln -s ../../SSD_MODULE/ssd_util.h					../hw/ssd_util.h

# HEADER FILE
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl_type.h				../hw/ftl_type.h
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl.h					../hw/ftl.h
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl_mapping_manager.h			../hw/ftl_mapping_manager.h
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl_inverse_mapping_manager.h		../hw/ftl_inverse_mapping_manager.h
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl_gc_manager.h			../hw/ftl_gc_manager.h
ln -s ../../FTL_SOURCE/PERF_MODULE/ftl_perf_manager.h			../hw/ftl_perf_manager.h

ln -s ../../SSD_MODULE/ssd_io_manager.h					../hw/ssd_io_manager.h
ln -s ../../SSD_MODULE/ssd_log_manager.h				../hw/ssd_log_manager.h

# SOURCE FILLE
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl.c					../hw/ftl.c
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl_mapping_manager.c			../hw/ftl_mapping_manager.c
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl_inverse_mapping_manager.c		../hw/ftl_inverse_mapping_manager.c
ln -s ../../FTL_SOURCE/PAGE_MAP/ftl_gc_manager.c			../hw/ftl_gc_manager.c
ln -s ../../FTL_SOURCE/PERF_MODULE/ftl_perf_manager.c			../hw/ftl_perf_manager.c

ln -s ../../SSD_MODULE/ssd_io_manager.c					../hw/ssd_io_manager.c
ln -s ../../SSD_MODULE/ssd_log_manager.c 				../hw/ssd_log_manager.c

# Monitor setting
ln -s ../../MONITOR/SSD_MONITOR_PM/ssd_monitor_p 			../x86_64-softmmu/ssd_monitor

# SSD_configuration setting
ln -s ../../../CONFIG/ssd.conf						../x86_64-softmmu/data/ssd.conf
ln -s ../../CONFIG/vssim_config_manager.h				../hw/vssim_config_manager.h
ln -s ../../CONFIG/vssim_config_manager.c				../hw/vssim_config_manager.c

