#!/usr/bin/env python3
import math
import os
import sys

MARGIN_FLOOR = 0.15
MARGIN_CAP = 0.50
MARGIN_SPREAD_MULT = 2.0
SCHED_MARGIN = 0.75
SPREAD_FLAG_THRESHOLD = 0.05
PERCENT = 100.0
FLOAT_BOUND_DECIMALS = 4
ZERO_MAX = 0          # an observed max of zero has no meaningful spread
NO_SPREAD = 0.0       # the spread reported for that degenerate case
SCALE_BASE = 1.0      # margins are applied as SCALE_BASE -/+ m

BOUNDED = [
    "logical_write_count", "write_count", "write_amplification",
    "gc_invocations", "disk_utilization_avg",
]
TIGHT_METRICS = {"logical_write_count"}
SCHED_METRICS = {"gc_invocations"}
INT_METRICS = {"write_count", "logical_write_count", "read_count", "gc_invocations",
               "gc_background"}


def margin(spread):
    return min(MARGIN_CAP, max(MARGIN_FLOOR, MARGIN_SPREAD_MULT * spread))


def bounds_for(values, metric=""):
    lo, hi = min(values), max(values)
    spread = NO_SPREAD if hi == ZERO_MAX else (hi - lo) / hi
    m = SCHED_MARGIN if metric in SCHED_METRICS else margin(spread)
    return lo * (SCALE_BASE - m), hi * (SCALE_BASE + m), lo, hi, spread


def parse(path):
    data = {}
    case = None
    with open(path) as fh:
        for raw in fh:
            line = raw.strip()
            if line.startswith("#") or not line:
                continue
            if line.startswith("test case:"):
                case = line.split(":", 1)[1].strip()
                data.setdefault(case, {})
            elif line.startswith("run #"):
                continue
            elif case is not None and "=" in line:
                key, _, val = line.partition("=")
                try:
                    fval = float(val.strip())
                except ValueError:
                    continue
                data[case].setdefault(key.strip(), []).append(fval)
    return data


def fmt_obs(metric, v):
    return ("%d" % round(v)) if metric in INT_METRICS else ("%g" % v)


def fmt_bound(metric, x, is_lo):
    if metric in INT_METRICS:
        return str(int(math.floor(x)) if is_lo else int(math.ceil(x)))
    return "%.*f" % (FLOAT_BOUND_DECIMALS, x)


def emit_metrics(case, metrics):
    out = []
    for metric in BOUNDED:
        vals = metrics.get(metric)
        if not vals:
            continue
        lo, hi = min(vals), max(vals)
        if metric in TIGHT_METRICS:
            blo, bhi = lo, hi
            if lo != hi:
                out.append("#   %-22s !! EXPECTED-DETERMINISTIC METRIC VARIED [%s, %s] across runs"
                           " -- investigate (event loss? nondeterministic traffic?)"
                           % (metric, fmt_obs(metric, lo), fmt_obs(metric, hi)))
            else:
                out.append("#   %-22s observed %s (deterministic; exact gate)"
                           % (metric, fmt_obs(metric, lo)))
        else:
            blo, bhi, lo, hi, spread = bounds_for(vals, metric)
            flag = ("  <-- SPREAD>%g%%" % (SPREAD_FLAG_THRESHOLD * PERCENT)) if spread > SPREAD_FLAG_THRESHOLD else ""
            out.append("#   %-22s observed [%s, %s] spread=%.2f%%%s"
                       % (metric, fmt_obs(metric, lo), fmt_obs(metric, hi), spread * PERCENT, flag))
        base = "BOUND_%s_%s" % (case.upper(), metric.upper())
        out.append("%s_MIN=%s" % (base, fmt_bound(metric, blo, True)))
        out.append("%s_MAX=%s" % (base, fmt_bound(metric, bhi, False)))
    return out


def emit(data):
    out = []
    out.append("# host_tests_bounds.env  (generated by derive_bounds.py from HOST_TESTS_CASES_METRICS.md)")
    out.append("# Tolerant: bound = [min*(1-m), max*(1+m)], m = clamp(%g*spread, %.2f, %.2f), spread = (max-min)/max."
               % (MARGIN_SPREAD_MULT, MARGIN_FLOOR, MARGIN_CAP))
    out.append("# Scheduling-dependent (%s): m = %.2f regardless of spread -- the count varies by host"
               % (", ".join(sorted(SCHED_METRICS)), SCHED_MARGIN))
    out.append("#   scheduling (CI observed 4765-5592 vs local 7923-9803 for the sector case); the wide band")
    out.append("#   still catches GC-dead and GC-runaway while GC effects are gated by write_count,")
    out.append("#   write_amplification and disk_utilization.")
    out.append("# Tight (%s): bound = observed value exactly (deterministic pipeline sentinel)."
               % ", ".join(sorted(TIGHT_METRICS)))
    out.append("# No bounds for the RUN_HEAVY=1 suites (ssd_write_read_tests, onfi_ops_tests) by design: they")
    out.append("#   run report-only -- no 5-run characterization exists at their 6-20M event volume. To gate")
    out.append("#   them, characterize and add BOUND_SSD_WRITE_READ_TESTS_* / BOUND_ONFI_OPS_TESTS_* entries.")
    out.append("")
    for case, metrics in data.items():
        runs = max((len(v) for v in metrics.values()), default=0)
        out.append("# --- %s  (n=%d runs) ---" % (case, runs))
        out.extend(emit_metrics(case, metrics))
        out.append("")
    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


def main(argv):
    here = os.path.dirname(os.path.abspath(__file__))
    md = argv[1] if len(argv) > 1 else os.path.normpath(
        os.path.join(here, "..", "..", "eVSSIM", "docs", "HOST_TESTS_CASES_METRICS.md"))
    out_path = argv[2] if len(argv) > 2 else os.path.join(here, "host_tests_bounds.env")
    data = parse(md)
    if not data:
        sys.stderr.write("derive_bounds.py: no data parsed from %s\n" % md)
        return 1
    with open(out_path, "w") as fh:
        fh.write(emit(data))
    sys.stderr.write("derive_bounds.py: wrote %s from %s (%d cases)\n" % (out_path, md, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
