#!/usr/bin/env python3
"""
derive_bounds.py — derive per-case metric bounds from a characterization run.

Reads eVSSIM/docs/HOST_TESTS_CASES_METRICS.md (the run #1..#N matrix produced by
docker-test-host-elk.sh with RUNS>1) and writes infra/ELK/host_tests_bounds.env,
the bounds docker-test-host-elk.sh asserts against in CI (RUNS=1). Keeping both
files generated from the SAME runs is what guarantees the committed sample values
always fall inside the committed bounds.

Per metric, across the N runs:
    spread = (max - min) / max               (0 when max == 0)
    margin = clamp(2 * spread, 0.15, 0.50)
    bound  = [ min * (1 - margin), max * (1 + margin) ]
The 0.15 floor absorbs background-GC timing variance so the gate is not flaky;
the 0.50 cap stops a genuinely unstable metric from getting a meaningless bound.
Count metrics are widened outward to whole numbers (floor min / ceil max).

Usage:
    derive_bounds.py [METRICS_MD] [BOUNDS_ENV]   # default paths relative to this file
    derive_bounds.py --selftest                  # verify the formula, no I/O
"""
import math
import os
import sys

MARGIN_FLOOR = 0.15
MARGIN_CAP = 0.50

# Gated metrics (must match METRICS in docker-test-host-elk.sh). IOPS / speed are
# report-only there, so they get no bounds here.
BOUNDED = [
    "logical_write_count", "write_count", "write_amplification",
    "gc_invocations", "disk_utilization_avg",
]
# Deterministic pipeline sentinel: bound EXACTLY at the observed value. Any drift
# in CI then means the pipeline dropped or added events — the whole point of it.
TIGHT_METRICS = {"logical_write_count"}
INT_METRICS = {"write_count", "logical_write_count", "read_count", "gc_invocations",
               "gc_background"}


def margin(spread):
    return min(MARGIN_CAP, max(MARGIN_FLOOR, 2.0 * spread))


def bounds_for(values):
    """Return (bound_lo, bound_hi, observed_min, observed_max, spread)."""
    lo, hi = min(values), max(values)
    spread = 0.0 if hi == 0 else (hi - lo) / hi
    m = margin(spread)
    return lo * (1.0 - m), hi * (1.0 + m), lo, hi, spread


def parse(path):
    """Parse the metrics doc -> {case: {metric: [values...]}} (in file order)."""
    data = {}
    case = None
    with open(path) as fh:
        for raw in fh:
            line = raw.strip()
            if line.startswith("#") or not line:
                continue
            if line.startswith("test case:"):
                case = line.split(":", 1)[1].strip()
                data.setdefault(case, {})
            elif line.startswith("run #"):
                continue
            elif case is not None and "=" in line:
                key, _, val = line.partition("=")
                try:
                    fval = float(val.strip())
                except ValueError:
                    continue
                data[case].setdefault(key.strip(), []).append(fval)
    return data


def fmt_obs(metric, v):
    return ("%d" % round(v)) if metric in INT_METRICS else ("%g" % v)


def fmt_bound(metric, x, is_lo):
    if metric in INT_METRICS:
        return str(int(math.floor(x)) if is_lo else int(math.ceil(x)))
    return "%.4f" % x


def emit(data):
    out = []
    out.append("# host_tests_bounds.env  (generated by derive_bounds.py from HOST_TESTS_CASES_METRICS.md)")
    out.append("# Tolerant: bound = [min*(1-m), max*(1+m)], m = clamp(2*spread, 0.15, 0.50), spread = (max-min)/max.")
    out.append("# Tight (%s): bound = observed value exactly (deterministic pipeline sentinel)."
               % ", ".join(sorted(TIGHT_METRICS)))
    out.append("")
    for case, metrics in data.items():
        runs = max((len(v) for v in metrics.values()), default=0)
        out.append("# --- %s  (n=%d runs) ---" % (case, runs))
        for metric in BOUNDED:
            vals = metrics.get(metric)
            if not vals:
                continue
            lo, hi = min(vals), max(vals)
            if metric in TIGHT_METRICS:
                blo, bhi = lo, hi   # exact gate, no tolerance
                if lo != hi:
                    out.append("#   %-22s !! EXPECTED-DETERMINISTIC METRIC VARIED [%s, %s] across runs"
                               " -- investigate (event loss? nondeterministic traffic?)"
                               % (metric, fmt_obs(metric, lo), fmt_obs(metric, hi)))
                else:
                    out.append("#   %-22s observed %s (deterministic; exact gate)"
                               % (metric, fmt_obs(metric, lo)))
            else:
                blo, bhi, lo, hi, spread = bounds_for(vals)
                flag = "  <-- SPREAD>5%" if spread > 0.05 else ""
                out.append("#   %-22s observed [%s, %s] spread=%.2f%%%s"
                           % (metric, fmt_obs(metric, lo), fmt_obs(metric, hi), spread * 100, flag))
            base = "BOUND_%s_%s" % (case.upper(), metric.upper())
            out.append("%s_MIN=%s" % (base, fmt_bound(metric, blo, True)))
            out.append("%s_MAX=%s" % (base, fmt_bound(metric, bhi, False)))
        out.append("")
    return "\n".join(out) + "\n"


def selftest():
    # documented examples must reproduce exactly (validates the formula offline).
    blo, bhi, lo, hi, spread = bounds_for([25.382, 28.5924])      # sector read_iops
    assert abs(spread - 0.1123) < 1e-3, spread
    assert abs(blo - 19.6821) < 1e-3, blo
    assert abs(bhi - 35.0132) < 1e-3, bhi
    blo, bhi, *_ = bounds_for([6366, 7664])                        # sector gc_invocations
    assert math.floor(blo) == 4209 and math.ceil(bhi) == 10260, (blo, bhi)
    blo, bhi, *_ = bounds_for([17896, 17896])                      # zero-variance count -> 0.15 floor
    assert math.floor(blo) == 15211 and math.ceil(bhi) == 20581, (blo, bhi)
    blo, bhi, lo, hi, spread = bounds_for([0.706887, 0.738923])    # disk_utilization_avg
    assert abs(blo - 0.6009) < 1e-3 and abs(bhi - 0.8498) < 1e-3, (blo, bhi)
    blo, bhi, *_ = bounds_for([0, 0])                              # all-zero -> [0, 0]
    assert blo == 0 and bhi == 0
    print("derive_bounds.py selftest: OK")


def main(argv):
    if "--selftest" in argv:
        selftest()
        return 0
    here = os.path.dirname(os.path.abspath(__file__))
    md = argv[1] if len(argv) > 1 else os.path.normpath(
        os.path.join(here, "..", "..", "eVSSIM", "docs", "HOST_TESTS_CASES_METRICS.md"))
    out_path = argv[2] if len(argv) > 2 else os.path.join(here, "host_tests_bounds.env")
    data = parse(md)
    if not data:
        sys.stderr.write("derive_bounds.py: no data parsed from %s\n" % md)
        return 1
    with open(out_path, "w") as fh:
        fh.write(emit(data))
    sys.stderr.write("derive_bounds.py: wrote %s from %s (%d cases)\n" % (out_path, md, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
