---
#
# Pull Filebeat and start container
#

- name: Start filebeat container, connect to network and link
  become: yes
  retries: 10
  delay: 10
  docker_container:
   name: filebeat
   image: docker.elastic.co/beats/filebeat:8.3.2
   state: started
   auto_remove: yes
   links:
    - "elasticsearch:elasticsearch"
   command:
    - filebeat
    - -e
    - --strict.perms=false
   volumes:
    - "/code/logs/:/logs/"
    - "{{ ansible_env.HOME }}/elk-config/filebeat/filebeat-conf.yml:/usr/share/filebeat/filebeat.yml"
   timeout: 300