---
#
# Pull Kibana and start container
#

- name: Start kibana container, connect to network and link
  become: yes
  docker_container:
   name: kibana
   image: docker.elastic.co/kibana/kibana:8.3.2
   state: started
   auto_remove: yes
   env:
     ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
   links:
    - "elasticsearch:elasticsearch"
   ports:
    - "5601:5601"
