# tasks for creating directories for filebeat

- name: Create filebeat config directory
  file:
    path: "{{ ansible_env.HOME }}/elk-config/filebeat"
    state: directory
    recurse: yes

- name: Copy filebeat config file
  copy:
    src: filebeat-conf.yml
    dest: "{{ ansible_env.HOME }}/elk-config/filebeat/filebeat-conf.yml"

#include the role that creates elasticsearch docker container
- include: elasticsearch.yml

#include the role that creates kibana docker container
- include: kibana.yml

#include the role that creates filebeat docker container
- include: filebeat.yml

# Pause for 30 seconds to allow elastic stack to start.
- pause:
    prompt: "Pause for 30 seconds to allow elastic stack to start"
    seconds: 30
