- name: check whether qt3 exists
  stat: "path=/usr/lib64/qt-3.3/bin/qmake"
  register: qt3_reg

- fail:
    msg: "qt3 binaries are required, and should be under path=/usr/lib64/qt-3.3/bin/qmake."
  when: qt3_reg.stat.exists == false
