#!/bin/bash
# Usage: clush [ file | -c list ] command ...
# 	file holds a list of hosts to run the command on
#	list is a space delimited list of such hosts

progname=`basename $0`

if [[ $# = 0 || $1 = -h || $1 = --help ]]; then
	echo "Usage: $progname [ file | -c list ] command ..." 1>&2
	exit 1
fi

if [ $1 = "-c" ]; then
	hosts="$2"
	shift
else
	if [ ! -f $1 ]; then
		echo $progname: $1 not found 1>&2
		exit 1
	fi
	hosts=`cat $1`
fi
shift
for i in `eval echo $hosts`; do
	ssh $i `dirname $0`/clux $* &
done
wait
