#!/bin/bash

export EVSSIM_ENVIRONMENT=yes

export EVSSIM_ROOT_PATH=$(realpath $(dirname $0)/../../..)
export EVSSIM_EXTERNAL_UID=$UID
export EVSSIM_ENV_HASH=$(md5sum $0 | cut -d " " -f 1)
export EVSSIM_ENV_PATH=$(realpath $0)

export EVSSIM_SIMULATOR_FOLDER=simulator
export EVSSIM_BUILDER_FOLDER=simulator/infra/builder
export EVSSIM_KERNEL_DIST=3.16.2
export EVSSIM_KERNEL_FOLDER=3.16.2/linux-3.16.2
export EVSSIM_NVME_CLI_FOLDER=nvme-cli
export EVSSIM_NVME_COMPLIANCE_FOLDER=nvmeCompl
export EVSSIM_DATA_FOLDER=data
export EVSSIM_DIST_FOLDER=dist

export EVSSIM_KCONFIG="CONFIG_BLK_DEV_NVME=m"

export EVSSIM_QEMU_IMAGE=system.img
export EVSSIM_QEMU_IMAGE_SIZE=4g
export EVSSIM_QEMU_UBUNTU_DEBOOTSTRAP_CACHE=deboostrap.tar
export EVSSIM_QEMU_UBUNTU_SYSTEM=trusty
export EVSSIM_QEMU_UBUNTU_USERNAME=esd
export EVSSIM_QEMU_UBUNTU_PASSWORD=esd
export EVSSIM_QEMU_UBUNTU_ROOT_PASSWORD=root
export EVSSIM_QEMU_FOLDER=$EVSSIM_SIMULATOR_FOLDER/eVSSIM/QEMU
export EVSSIM_QEMU_PORT=2222
export EVSSIM_QEMU_VNC=0

export EVSSIM_DOCKER_ROOT_PATH=/code
export EVSSIM_DOCKER_IMAGE_NAME=evssim
export EVSSIM_DOCKER_PORTS=2222:2222,2003:2003,5900:5900

export EVSSIM_GUEST_ROOT_PATH=/home/$EVSSIM_QEMU_UBUNTU_USERNAME
export EVSSIM_GUEST_MOUNT_POINT=/mnt/guest

export EVSSIM_RUNTIME_STORAGE_STRATEGY=1
export EVSSIM_RUNTIME_SSD_CONF_TEMPLATE=$EVSSIM_ROOT_PATH/$EVSSIM_BUILDER_FOLDER/docker/ssd.conf.template

export COMPILATION_GCC=gcc-4.6
export COMPILATION_CFLAGS=-Wno-error=cpp

export EVSSIM_CREATE_FOLDERS="$EVSSIM_DATA_FOLDER $EVSSIM_DIST_FOLDER"
