#!/bin/bash
source ./builder.sh

# Make a fresh copy
IMAGE_PATH=$EVSSIM_ROOT_PATH/$EVSSIM_DIST_FOLDER/$EVSSIM_QEMU_IMAGE
IMAGE_PATH_TEMPLATE=$EVSSIM_ROOT_PATH/$EVSSIM_DIST_FOLDER/$EVSSIM_QEMU_IMAGE".template"
cp -f $IMAGE_PATH_TEMPLATE $IMAGE_PATH

# Run qemu
evssim_qemu_attached
