version: "3.9"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.3.2"
    ports:
      - "9200:9200"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
  kibana:
    image: "docker.elastic.co/kibana/kibana:8.3.2"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200/"
  filebeat:
    image: "docker.elastic.co/beats/filebeat:8.3.2"
    volumes:
      - "${WORKSPACE}/logs:/logs/"
      - "./config/filebeat-conf.yaml:/usr/share/filebeat/filebeat.yml:ro"
    command:
      - filebeat
      - -e
      - --strict.perms=false