version: "3.9"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.3.2"
    ports:
      - "9200"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  kibana:
    image: "docker.elastic.co/kibana/kibana:8.3.2"
    ports:
      - "5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200/"
  filebeat:
    image: "docker.elastic.co/beats/filebeat:8.3.2"
    environment:
      ELK_ELASTICSEARCH_HOSTNAME: "elasticsearch"
      ELK_ELASTICSEARCH_EXTERNAL_PORT: "9200"
    volumes:
      - "${WORKSPACE}/logs:/logs/"
      - "${WORKSPACE}/simulator/infra/elk/config/filebeat-conf.yaml:/usr/share/filebeat/filebeat.yml:ro"
    command:
      - filebeat
      - -e
      - --strict.perms=false
networks:
  default:
    name: "${DOCKER_COMPOSE_PROJECT}"
