- name: start guest with new kernel to run tests
  shell: "../x86_64-softmmu/qemu-system-x86_64 -m {{memory}} -smp {{smp}} -hda '{{hda_img}}' -device nvme -redir tcp:{{guest_ssh_port}}::22 -nographic -vnc :0  -daemonize -pidfile '{{qemu_pid_file}}' -machine {{qemu_machine}} -kernel '{{dest}}/vmlinuz-3.16.2' -initrd '{{dest}}/initrd.img-3.16.2' -append 'BOOT_IMAGE=/boot/vmlinuz-3.16.2 root=UUID=063018ec-674c-4c3e-a976-ac4fa950864f ro'"
  args:
    chdir: "{{ dest }}/eVSSIM/QEMU/hw"
  become: yes
  tags: qemu

- include: qemu_wait_while_starting.yml

- debug: msg="Done starting from the prepared guest image"
  tags: qemu
