- name: waiting for guest to start
  wait_for:
  args:
    port: "{{guest_ssh_port}}"
    search_regex: OpenSSH
    timeout: 10000
  tags: qemu

- name: ssh into guest
  shell: "{{ guest_ssh_cmd }} uname"
  register: guest_uname
  tags: qemu

